version: '3.8'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
    volumes:
      - ./src:/var/www/html
    command: bash -c "composer install & php artisan serve --host=0.0.0.0 --port=8000"